### ISSUE TITLE
<- replaced by easy.layout

### ISSUE THREAD

**Issue by jordibruin** [nakiostudio/EasyPeasy#72]
I noticed that the Swift 4 syntax uses the new easy.layout syntax instead of <-.

Is there any particular reason for this? I've grown quite fond of <- and I feel like easy.layout will add a lot of redundant code in my auto layout functions.

Thanks.

**Comment by jordibruin** [comment]
Just saw the other issue that talks about this https://github.com/nakiostudio/EasyPeasy/issues/69.

While I kinda understand the points made there, it still feels like one of the main goals of this great library to me (cleaner auto layout with less code) has now taken a beating.

**Comment by nakiostudio** [comment]
Hi @jordibruin 👋 

That's correct. From:
```swift
view <- [
  Top(12),
  Left(20).to(otherView)
]
```

Now it's:
```swift
view.easy.layout(
  Top(12),
  Left(20).to(otherView)
)

// or

view.easy.layout([
  Top(12),
  Left(20).to(otherView)
])
```


But quoting myself from #71:

>I knew this wasn't going to satisfy every developer but I think it's a sensible change as the `<-` operator was one of the reasons for many devs to not to choose EasyPeasy. Also because after 3 years of Swift custom operators are in disuse for API designing.
However, you can stick to EasyPeasy `1.5.1` as deprecating those methods was the only change introduced on `1.6.0`. Another option is to drag [this file](https://gist.github.com/nakiostudio/543662179917eefe2db70cd6e1b81e5d) to your project to keep using the custom operator with future versions without dealing with deprecation warnings.

I also preferred the previous style and I agree that part of the library essence has been lost, but if I've taken this decision it's because of the opinion received from many devs.

Let's see how fast we get used to it!

**Comment by jordibruin** [comment]
Hi @nakiostudio , thanks for the reply!

You're making  lot of valid points so I'll try to get used to it instead of trying to stick to the past.

Small sidetone, when would you use the [ ] when using easy.layout? Are the two examples the exact same otherwise?

**Comment by nakiostudio** [comment]
Yes @jordibruin, both are the same but the case with square brackets is mean to be used if you want a `.when` closure affecting all attributes in an array. i.e.

``swift
view.easy.layout([
    Leading(20), 
    Top(20),
     Trailing(20)
].when { Device() == .iPad })
```
